# Copyright 2020-2023 The MathWorks, Inc

# Workflow to release MATLAB Jupyter Integration to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel pytest
          python3 -m pip install .[dev]

      - name: Run Python Tests
        run: python3 -m pytest

  build_and_publish_pypi:
    needs: [python_tests]
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel hatch

      - name: Build Source and Binary wheel distributions
        run: python3 -m hatch build -t wheel

      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          verbose: true
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}
