# Copyright 2020-2023 The MathWorks, Inc

# Workflow to release MATLAB Jupyter Integration to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  call-unit-tests:
    # Runs unit tests
    uses: ./.github/workflows/run-unit-tests.yml

  build_and_publish_pypi:
    # TODO: Add integration-tests as a dependency to
    # the release pipeline.
    needs: [call-unit-tests]
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel hatch

      - name: Build Source and Binary wheel distributions
        run: python3 -m hatch build -t wheel

      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          verbose: true
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}
